Changes in Teacher Screen
annechko/attendance-management pull request #11
Opened 2024-02-29 09:05 UTC by butchdc

2024-02-29 21:58 UTC, annechko requested changes

2024-02-29 21:58 UTC, annechko commented on app/src/Controller/Teacher/TeacherToSubjectToIntakeController.php
> -#[Route('/teacher/teacher-to-subject-to-intake')]
@butchdc now you have 2 different action functions for the same URL,
you want to make sure every link is unique, currently, there are the same links and 2 different handlers
#[Route('/teacher/')]
#[Route('/teacher/')]
app/src/Controller/Teacher/HomeController.php
app/src/Controller/Teacher/TeacherToSubjectToIntakeController.php

2024-02-29 22:23 UTC, butchdc commented on app/src/Controller/Teacher/TeacherToSubjectToIntakeController.php
> -#[Route('/teacher/teacher-to-subject-to-intake')]
@annechko ... Understood I realize I didn't clean it up properly, but the plan is to remove TeacherToSubjectIntakeController since all its functionality is now incorporated into HomeController. I'll fix this later. Thanks for pointing it out. ;)

2024-03-02 07:16 UTC, butchdc commented on app/src/Controller/Teacher/TeacherToSubjectToIntakeController.php
> -#[Route('/teacher/teacher-to-subject-to-intake')]
I have removed TeacherToSubjectToIntakeController code should now be clean

2024-03-02 07:54 UTC, merged